<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='details',
        ),
    ]

# Generated by Django 6.0.4 on 2026-06-13 06:55

=======
 
>>>>>>> d3a2ec70debcfc3c365549409ecc2e1e5748f1a7
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='details',
        ),
    ]
