# Generated by Django 6.0.6 on 2026-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_no_product_size_same_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='brandName',
        ),
    ]
