# Generated by Django 6.0.6 on 2026-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_stock_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='productImageFive',
        ),
        migrations.AddField(
            model_name='product',
            name='productImageFour',
            field=models.ImageField(default='hello', upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productImageOne',
            field=models.ImageField(default='helo', upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productImageThree',
            field=models.ImageField(default='we', upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productImageTwo',
            field=models.ImageField(default='ef', upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='uprdescription',
            field=models.TextField(blank=True),
        ),
    ]
