# Generated by Django 6.0.6 on 2026-06-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_productimage_product_productimagefive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImageOne',
            new_name='productImage',
        ),
    ]
