# Generated by Django 6.0.6 on 2026-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_productname_product_brandname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='no product size same',
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brandName', 'size', 'category'), name='no product size same'),
        ),
    ]
